# -*- coding: utf-8 -*-
"""
Created on Wed Apr 22 13:17:09 2020

@author: 汪嘉川
"""

seq1='''MLCRAACSTGRRLGPVAGAAGSRHKHSLPDLPYDYGALEPHINAQIMQLHHSKHHAAY
VNNLNATEEKYHEALAKGDVTTQVALQPALKFNGGGHINHTIFWTNLSPKGGGEPKGE
LLEAIKRDFGSFEKFKEKLTAVSVGVQGSGWGWLGFNKEQGRLQIAACSNQDPLQGTTG
LIPLLGIDVWEHAYYLQYKNVRPDYLKAIWNVINWENVTERYTACKK'''
seq2='''WNGFSEWWTHEVDYNQKLTIENNQRPKIHEHEQWGLRQSPPPPKLCCPTCQMCERM
RHQNRFAPLMEVGCRCMCWFHDWWVISVGTWLHTVIMYMMWPKRFHHNECPKACF
RTTYTRKNHHALYWMLFEMCCYDQDVVWSKTHIFTTVRDIEVYVEQVFFIWGPLCHV
AIACYEPVKTIRRRIPMYLCRHCIRGDNSYLLACCSIIYYFYHHMSYYGVLDIL'''
edit_distance	=	0
for	i	in	range(len(seq1)): 
    	if	seq1[i]!=seq2[i]:
            	edit_distance	+=	1
print(edit_distance)
print(len(seq2))